# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tutorials By Nick
email: nick@tutorialsbynick.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I put tutorials on how to program and
  use them on the computer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tutorialsbynick.com" # the base hostname & protocol for your site
twitter_username: nicholasbday
github_username: nicholasday

highlighter: pygments

# Build settings
markdown: kramdown
